### ISSUE TITLE
Getting few compile error

### ISSUE THREAD

**Issue by bipul-mohanto** [phgphg777/DXR-PathTracer#3]
Hi!

I have RTX hardware support, and using MSVS 2019 (x64) with Windows SDK Version 10.0. While compiling your main.cpp in  DXRPathTracer, it is resulting few errors: 

![issue](https://user-images.githubusercontent.com/12484581/148771236-219c6975-b162-44b2-9dd2-d3846f368b43.PNG)

**Comment by phgphg777** [comment]
I think your compiler option does not allow some c++11 features. 
And the following link may help you:

https://docs.microsoft.com/en-us/cpp/build/reference/zc-rvaluecast-enforce-type-conversion-rules?view=msvc-170
